/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;
import static javaapplication1.JDModificatarifa.jtid;
import javax.swing.JTable;
import simplemysql.SimpleMySQL;
import simplemysql.SimpleMySQLResult;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jonatan
 */

public class JDTarifas extends javax.swing.JDialog {
DefaultTableModel tablausuarios= new DefaultTableModel();
    /**
     * Creates new form JDTarifas
     */

   
 
           
    public JDTarifas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
       
        
        this.JTablausuarios.setModel(tablausuarios);
        this.tablausuarios.addColumn("ID");
        this.tablausuarios.addColumn("Descripcion");
        this.tablausuarios.addColumn("Fija");
        this.tablausuarios.addColumn("Dia");
 
        
        SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs;
        rs = mysql.Query ("SELECT * FROM tarifas");
        while (rs.next()){
                        String ID=rs.getString("ID");
                        String USUARIO=rs.getString("DESCRIPCION");
                        String FIJA=rs.getString("FIJA");
                        String DIA=rs.getString("DIA");
                        Object fila []= { ID,USUARIO,FIJA, DIA};
                        this.tablausuarios.addRow(fila);
         }
        
       
        
        rs.close(); 
        this.JTablausuarios.changeSelection(0, 0, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablausuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarifas"));

        JTablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablausuarios);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        JDNuevatarifa nu= new JDNuevatarifa(null, rootPaneCheckingEnabled);
        
        nu.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
        JDModificatarifa nu= new JDModificatarifa(null, rootPaneCheckingEnabled);
        int row = this.JTablausuarios.getSelectedRow();
        String elid=this.JTablausuarios.getValueAt(row, 0).toString();
        JDModificatarifa.jtid.setText(elid);
        
        SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs;
        rs = mysql.Query ("SELECT * FROM tarifas WHERE ID="+elid);
        Boolean boolean1 = Boolean.valueOf(rs.getString("FIJA"));
        while (rs.next()){
                        JDModificatarifa.jtdescripcion.setText(rs.getString("DESCRIPCION"));
                        JDModificatarifa.jctarifa.setSelected(boolean1);
                        JDModificatarifa.jtdia.setText(rs.getString("DIA"));
                        
                        JDModificatarifa.jfhorae1.setText(rs.getString("tiempoe1")); 
JDModificatarifa.jfhoraf1.setText(rs.getString("tiempos1")); 
JDModificatarifa.jthorat1.setText(rs.getString("tiempot1")); 
JDModificatarifa.jfhorae2.setText(rs.getString("tiempoe2")); 
JDModificatarifa.jfhoraf2.setText(rs.getString("tiempos2")); 
JDModificatarifa.jthorat2.setText(rs.getString("tiempot2")); 
JDModificatarifa.jfhorae3.setText(rs.getString("tiempoe3")); 
JDModificatarifa.jfhoraf3.setText(rs.getString("tiempos3")); 
JDModificatarifa.jthorat3.setText(rs.getString("tiempot3")); 
JDModificatarifa.jfhorae4.setText(rs.getString("tiempoe4")); 
JDModificatarifa.jfhoraf4.setText(rs.getString("tiempos4")); 
JDModificatarifa.jthorat4.setText(rs.getString("tiempot4")); 
JDModificatarifa.jfhorae5.setText(rs.getString("tiempoe5")); 
JDModificatarifa.jfhoraf5.setText(rs.getString("tiempos5")); 
JDModificatarifa.jthorat5.setText(rs.getString("tiempot5")); 
JDModificatarifa.jfhorae6.setText(rs.getString("tiempoe6")); 
JDModificatarifa.jfhoraf6.setText(rs.getString("tiempos6")); 
JDModificatarifa.jthorat6.setText(rs.getString("tiempot6")); 
JDModificatarifa.jfhorae7.setText(rs.getString("tiempoe7")); 
JDModificatarifa.jfhoraf7.setText(rs.getString("tiempos7")); 
JDModificatarifa.jthorat7.setText(rs.getString("tiempot7")); 
JDModificatarifa.jfhorae8.setText(rs.getString("tiempoe8")); 
JDModificatarifa.jfhoraf8.setText(rs.getString("tiempos8")); 
JDModificatarifa.jthorat8.setText(rs.getString("tiempot8")); 
JDModificatarifa.jfhorae9.setText(rs.getString("tiempoe9")); 
JDModificatarifa.jfhoraf9.setText(rs.getString("tiempos9")); 
JDModificatarifa.jthorat9.setText(rs.getString("tiempot9")); 
JDModificatarifa.jfhorae10.setText(rs.getString("tiempoe10")); 
JDModificatarifa.jfhoraf10.setText(rs.getString("tiempos10")); 
JDModificatarifa.jthorat10.setText(rs.getString("tiempot10")); 
JDModificatarifa.jfhorae11.setText(rs.getString("tiempoe11")); 
JDModificatarifa.jfhoraf11.setText(rs.getString("tiempos11")); 
JDModificatarifa.jthorat11.setText(rs.getString("tiempot11")); 
JDModificatarifa.jfhorae12.setText(rs.getString("tiempoe12")); 
JDModificatarifa.jfhoraf12.setText(rs.getString("tiempos12")); 
JDModificatarifa.jthorat12.setText(rs.getString("tiempot12")); 
JDModificatarifa.jfhorae13.setText(rs.getString("tiempoe13")); 
JDModificatarifa.jfhoraf13.setText(rs.getString("tiempos13")); 
JDModificatarifa.jthorat13.setText(rs.getString("tiempot13")); 
JDModificatarifa.jfhorae14.setText(rs.getString("tiempoe14")); 
JDModificatarifa.jfhoraf14.setText(rs.getString("tiempos14")); 
JDModificatarifa.jthorat14.setText(rs.getString("tiempot14")); 
JDModificatarifa.jfhorae15.setText(rs.getString("tiempoe15")); 
JDModificatarifa.jfhoraf15.setText(rs.getString("tiempos15")); 
JDModificatarifa.jthorat15.setText(rs.getString("tiempot15")); 
JDModificatarifa.jfhorae16.setText(rs.getString("tiempoe16")); 
JDModificatarifa.jfhoraf16.setText(rs.getString("tiempos16")); 
JDModificatarifa.jthorat16.setText(rs.getString("tiempot16")); 
JDModificatarifa.jfhorae17.setText(rs.getString("tiempoe17")); 
JDModificatarifa.jfhoraf17.setText(rs.getString("tiempos17")); 
JDModificatarifa.jthorat17.setText(rs.getString("tiempot17")); 
JDModificatarifa.jfhorae18.setText(rs.getString("tiempoe18")); 
JDModificatarifa.jfhoraf18.setText(rs.getString("tiempos18")); 
JDModificatarifa.jthorat18.setText(rs.getString("tiempot18")); 
JDModificatarifa.jfhorae19.setText(rs.getString("tiempoe19")); 
JDModificatarifa.jfhoraf19.setText(rs.getString("tiempos19")); 
JDModificatarifa.jthorat19.setText(rs.getString("tiempot19")); 
JDModificatarifa.jfhorae20.setText(rs.getString("tiempoe20")); 
JDModificatarifa.jfhoraf20.setText(rs.getString("tiempos20")); 
JDModificatarifa.jthorat20.setText(rs.getString("tiempot20")); 
JDModificatarifa.jfhorae21.setText(rs.getString("tiempoe21")); 
JDModificatarifa.jfhoraf21.setText(rs.getString("tiempos21")); 
JDModificatarifa.jthorat21.setText(rs.getString("tiempot21")); 
JDModificatarifa.jfhorae22.setText(rs.getString("tiempoe22")); 
JDModificatarifa.jfhoraf22.setText(rs.getString("tiempos22")); 
JDModificatarifa.jthorat22.setText(rs.getString("tiempot22")); 
JDModificatarifa.jfhorae23.setText(rs.getString("tiempoe23")); 
JDModificatarifa.jfhoraf23.setText(rs.getString("tiempos23")); 
JDModificatarifa.jthorat23.setText(rs.getString("tiempot23")); 
JDModificatarifa.jfhorae24.setText(rs.getString("tiempoe24")); 
JDModificatarifa.jfhoraf24.setText(rs.getString("tiempos24")); 
JDModificatarifa.jthorat24.setText(rs.getString("tiempot24")); 
JDModificatarifa.jfhorae25.setText(rs.getString("tiempoe25")); 
JDModificatarifa.jfhoraf25.setText(rs.getString("tiempos25")); 
JDModificatarifa.jfhorat25.setText(rs.getString("tiempot25"));  
JDModificatarifa.jfhorae26.setText(rs.getString("tiempoe26")); 
JDModificatarifa.jfhoraf26.setText(rs.getString("tiempos26")); 
JDModificatarifa.jfhorat26.setText(rs.getString("tiempot26")); 
JDModificatarifa.jfhorae27.setText(rs.getString("tiempoe27")); 
JDModificatarifa.jfhoraf27.setText(rs.getString("tiempos27")); 
JDModificatarifa.jfhora27.setText(rs.getString("tiempot27")); 
JDModificatarifa.jfhorae28.setText(rs.getString("tiempoe28")); 
JDModificatarifa.jfhoraf28.setText(rs.getString("tiempos28")); 
JDModificatarifa.jfhora28.setText(rs.getString("tiempot28")); 
JDModificatarifa.jfhorae29.setText(rs.getString("tiempoe29")); 
JDModificatarifa.jfhoraf29.setText(rs.getString("tiempos29")); 
JDModificatarifa.jfhora29.setText(rs.getString("tiempot29")); 
JDModificatarifa.jfhorae30.setText(rs.getString("tiempoe30")); 
JDModificatarifa.jfhoraf30.setText(rs.getString("tiempos30")); 
JDModificatarifa.jfhorat30.setText(rs.getString("tiempot30")); 
JDModificatarifa.jfhorae31.setText(rs.getString("tiempoe31")); 
JDModificatarifa.jfhoraf31.setText(rs.getString("tiempos31")); 
JDModificatarifa.jfhora31.setText(rs.getString("tiempot31")); 
JDModificatarifa.jfhorae32.setText(rs.getString("tiempoe32")); 
JDModificatarifa.jfhoraf32.setText(rs.getString("tiempos32")); 
JDModificatarifa.jfhora32.setText(rs.getString("tiempot32")); 
JDModificatarifa.jfhorae33.setText(rs.getString("tiempoe33")); 
JDModificatarifa.jfhoraf33.setText(rs.getString("tiempos33")); 
JDModificatarifa.jthorat33.setText(rs.getString("tiempot33")); 
JDModificatarifa.jfhorae34.setText(rs.getString("tiempoe34")); 
JDModificatarifa.jfhoraf34.setText(rs.getString("tiempos34")); 
JDModificatarifa.jthorat34.setText(rs.getString("tiempot34")); 
JDModificatarifa.jfhorae35.setText(rs.getString("tiempoe35")); 
JDModificatarifa.jfhoraf35.setText(rs.getString("tiempos35")); 
JDModificatarifa.jthorat35.setText(rs.getString("tiempot35")); 
JDModificatarifa.jfhorae36.setText(rs.getString("tiempoe36")); 
JDModificatarifa.jfhoraf36.setText(rs.getString("tiempos36")); 
JDModificatarifa.jthorat36.setText(rs.getString("tiempot36")); 
JDModificatarifa.jfhorae37.setText(rs.getString("tiempoe37")); 
JDModificatarifa.jfhoraf37.setText(rs.getString("tiempos37")); 
JDModificatarifa.jthorat37.setText(rs.getString("tiempot37")); 
JDModificatarifa.jfhorae38.setText(rs.getString("tiempoe38")); 
JDModificatarifa.jfhoraf38.setText(rs.getString("tiempos38")); 
JDModificatarifa.jthorat38.setText(rs.getString("tiempot38")); 
JDModificatarifa.jfhorae39.setText(rs.getString("tiempoe39")); 
JDModificatarifa.jfhoraf39.setText(rs.getString("tiempos39")); 
JDModificatarifa.jthorat39.setText(rs.getString("tiempot39")); 
JDModificatarifa.jfhorae40.setText(rs.getString("tiempoe40")); 
JDModificatarifa.jfhoraf40.setText(rs.getString("tiempos40")); 
JDModificatarifa.jthorat40.setText(rs.getString("tiempot40")); 
JDModificatarifa.jfhorae41.setText(rs.getString("tiempoe41")); 
JDModificatarifa.jfhoraf41.setText(rs.getString("tiempos41")); 
JDModificatarifa.jthorat41.setText(rs.getString("tiempot41")); 
JDModificatarifa.jfhorae42.setText(rs.getString("tiempoe42")); 
JDModificatarifa.jfhoraf42.setText(rs.getString("tiempos42")); 
JDModificatarifa.jthorat42.setText(rs.getString("tiempot42")); 
JDModificatarifa.jfhorae43.setText(rs.getString("tiempoe43")); 
JDModificatarifa.jfhoraf43.setText(rs.getString("tiempos43")); 
JDModificatarifa.jthorat43.setText(rs.getString("tiempot43")); 
JDModificatarifa.jfhorae44.setText(rs.getString("tiempoe44")); 
JDModificatarifa.jfhoraf44.setText(rs.getString("tiempos44")); 
JDModificatarifa.jthorat44.setText(rs.getString("tiempot44")); 
JDModificatarifa.jfhorae45.setText(rs.getString("tiempoe45")); 
JDModificatarifa.jfhoraf45.setText(rs.getString("tiempos45")); 
JDModificatarifa.jthorat45.setText(rs.getString("tiempot45")); 
JDModificatarifa.jfhorae46.setText(rs.getString("tiempoe46")); 
JDModificatarifa.jfhoraf46.setText(rs.getString("tiempos46")); 
JDModificatarifa.jthorat46.setText(rs.getString("tiempot46")); 
JDModificatarifa.jfhorae47.setText(rs.getString("tiempoe47")); 
JDModificatarifa.jfhoraf47.setText(rs.getString("tiempos47")); 
JDModificatarifa.jthorat47.setText(rs.getString("tiempot47")); 
JDModificatarifa.jfhorae48.setText(rs.getString("tiempoe48")); 
JDModificatarifa.jfhoraf48.setText(rs.getString("tiempos48")); 
JDModificatarifa.jthorat48.setText(rs.getString("tiempot48")); 
                        
                       
         }
        
       
        
        rs.close(); 
        
        
        nu.setVisible(rootPaneCheckingEnabled);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDTarifas dialog = new JDTarifas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTablausuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
