/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import simplemysql.SimpleMySQL;
import simplemysql.SimpleMySQLResult;
/**
 *
 * @author Jonatan
 */
public class JFMenu extends javax.swing.JFrame {
 JITickets reporte=new JITickets();

NewJInternalFrame estacionados=new NewJInternalFrame();
    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        
this.desktop.add(reporte);
        //Maximizar formulario
        this.setExtendedState(this.MAXIMIZED_BOTH);
         JDLogin jdialog= new JDLogin(null, true);
      jdialog.setVisible(true);


        this.desktop.add(estacionados);
        estacionados.show();
        try {
            estacionados.setMaximum(true);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelprincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        Ventas = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        saliendo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("RESUMEN DEL DIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REPORTE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EMITIR/COBRAR TICKETS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelprincipalLayout = new javax.swing.GroupLayout(JPanelprincipal);
        JPanelprincipal.setLayout(JPanelprincipalLayout);
        JPanelprincipalLayout.setHorizontalGroup(
            JPanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelprincipalLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 831, Short.MAX_VALUE))
        );
        JPanelprincipalLayout.setVerticalGroup(
            JPanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2)
                .addComponent(jButton3))
        );

        desktop.setPreferredSize(new java.awt.Dimension(1200, 1010));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1218, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Cambiar de Usuario...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Catalogo de Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Tarifas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Parametros");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        Ventas.add(jMenu1);

        jMenu2.setText("Tickets");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem1.setText("Emisión de Tickets");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Resumen del dia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Reporte");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Abrir/Cerrar Corte");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator2);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Imprimir Corte");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        Ventas.add(jMenu2);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        saliendo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, 0));
        saliendo.setText("Salir");
        saliendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saliendoActionPerformed(evt);
            }
        });
        salir.add(saliendo);

        Ventas.add(salir);

        setJMenuBar(Ventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs;
        rs = mysql.Query ("SELECT * FROM cortes WHERE FECHAFIN IS NULL");
        if(rs.next()){
        JDCorte jdc= new JDCorte(this, rootPaneCheckingEnabled);
jdc.setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:
        
        }else{
        JDCorte1 jdc2= new JDCorte1(this, rootPaneCheckingEnabled);
jdc2.setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:
        
        
        }
       
rs.close();
        mysql.close();
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void saliendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saliendoActionPerformed
     System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_saliendoActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs;
        rs = mysql.Query ("SELECT * FROM cortes WHERE FECHAFIN IS NULL");
        if(rs.next()){
        
        JDEntradas jde= new JDEntradas(this, rootPaneCheckingEnabled);
jde.setVisible(rootPaneCheckingEnabled); 
jde.setAlwaysOnTop (true);// TODO add your handling code here:
        }else{
        showMessageDialog(null, "Debe iniciar un corte");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

         if("admin".equals(JDLogin.elusuario)){
             
        JDCortes jdc= new JDCortes(this, rootPaneCheckingEnabled);
jdc.setVisible(rootPaneCheckingEnabled);
        }else{
            JDError jde= new JDError(this, rootPaneCheckingEnabled);
            jde.setVisible(rootPaneCheckingEnabled);

        }
        
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

         if("admin".equals(JDLogin.elusuario)){
            JDPreferencias jdp = new JDPreferencias(this, rootPaneCheckingEnabled);
        jdp.setVisible(rootPaneCheckingEnabled);
        }else{
            JDError jde= new JDError(this, rootPaneCheckingEnabled);
            jde.setVisible(rootPaneCheckingEnabled);

        }
        
        
       
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

         if("admin".equals(JDLogin.elusuario)){
           JDTarifas jdt= new JDTarifas(this, rootPaneCheckingEnabled);
        jdt.setVisible(rootPaneCheckingEnabled);        // TODO add your handling code here:        // TODO add your handling code here:
        }else{
            JDError jde= new JDError(this, rootPaneCheckingEnabled);
            jde.setVisible(rootPaneCheckingEnabled);

        }
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        if("admin".equals(JDLogin.elusuario)){
            JDUsuarios cd= new JDUsuarios(this, rootPaneCheckingEnabled);
            cd.setVisible(rootPaneCheckingEnabled);
        }else{
            JDError jde= new JDError(this, rootPaneCheckingEnabled);
            jde.setVisible(rootPaneCheckingEnabled);

        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        JFMenu abrir=new JFMenu();
        abrir.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
reporte.hide();
estacionados.show();
        try {
            estacionados.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
estacionados.hide();
reporte.show();
        try {
            reporte.setMaximum(true);
        } catch (Exception e) {
        }
           
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
reporte.hide();
estacionados.show();
        try {
            estacionados.setMaximum(true);
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 estacionados.hide();
 
   reporte.tablapagados.setNumRows(0); 
        SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs=null;
        
         if(reporte.jTextField2.getText().equals("")){
        rs = mysql.Query ("SELECT * FROM estacionados");
        }else{ 
        if (reporte.jComboBox2.getSelectedItem().toString()=="Placas") {
                rs = mysql.Query ("SELECT * FROM estacionados WHERE PLACAS LIKE \"%"+reporte.jTextField2.getText()+"%\"");
            }else{
                rs = mysql.Query ("SELECT * FROM estacionados WHERE (TICKET LIKE \"%"+reporte.jTextField2.getText().replaceAll("[^\\d.]", "").replaceAll("0", "")+"%\" AND SERIE LIKE \"%"+reporte.jTextField2.getText().replaceAll("[0-9]", "")+"%\")");
            }
        
        }
        
       
        int contador=1;
        java.text.DecimalFormat nft = new  
java.text.DecimalFormat("#000000.###");  
nft.setDecimalSeparatorAlwaysShown(false); 
         DateFormat fold = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
         DateFormat fnew = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
         String SALIDA="";
        while (rs.next()){
     try {
         String ELID= String.valueOf(rs.getString("ID"));
         String TICKET=rs.getString("SERIE")+nft.format(Integer.parseInt(rs.getString("TICKET")));
         String PLACAS=rs.getString("PLACAS");
         String MARCA=rs.getString("MARCA");
         String ENTRADA=fnew.format(fold.parse(rs.getString("ENTRADA").replace(".0", "")));
         if (rs.getString("SALIDA")!= null && !rs.getString("SALIDA").isEmpty()) {
             try {
                 SALIDA=fnew.format(fold.parse(rs.getString("SALIDA").replace(".0", "")));
             } catch (ParseException ex) {
                 Logger.getLogger(JFMenu.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else{
             SALIDA=rs.getString("SALIDA");
         }
         String TIEMPO=rs.getString("TIEMPO");
         String DIAS=rs.getString("DIAS");
         String IMPORTE=rs.getString("IMPORTE");
         String TARIFA=rs.getString("TARIFA");
         String ESTATUS=rs.getString("ESTATUS");
         if (ESTATUS.equals("Registro")) {
             ESTATUS="ESTACIONADO";
         }
         String USUARIOEMISION=rs.getString("USUARIOEMISION");
         Object fila []= { ELID, TICKET, PLACAS, MARCA,ENTRADA,SALIDA,TIEMPO,DIAS,IMPORTE,TARIFA,ESTATUS,USUARIOEMISION};
         reporte.tablapagados.addRow(fila);
         contador++;
     } catch (ParseException ex) {
         Logger.getLogger(JFMenu.class.getName()).log(Level.SEVERE, null, ex);
     }

        }
        rs.close();
        mysql.close();
 
 
 
reporte.show();
        try {
            reporte.setMaximum(true);
        } catch (Exception e) {
        }        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 SimpleMySQL mysql;
        mysql = new SimpleMySQL();
        mysql.connect("localhost", "root", "x4899954", "estacionamientos");
        SimpleMySQLResult rs;
        rs = mysql.Query ("SELECT * FROM cortes WHERE FECHAFIN IS NULL");
        if(rs.next()){
        
        JDEntradas jde= new JDEntradas(this, rootPaneCheckingEnabled);
jde.setVisible(rootPaneCheckingEnabled); 
jde.setAlwaysOnTop (true);// TODO add your handling code here:
        }else{
        showMessageDialog(null, "Debe iniciar un corte");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
        
       
        
    }
public static class KeyListenerCustom implements KeyListener{
    private JDialog dialog=null;
    public KeyListenerCustom(JITickets dialog){
        System.out.println("Dialog!");
        
    }
    public void keyTyped(KeyEvent e) {

    }
 
    public void keyPressed(KeyEvent e) {
        
        
     if(e.getKeyCode()==KeyEvent.VK_F10){
        JITickets.jTextField2.setText("");
        
       
 }
        
    }
 
    public void keyReleased(KeyEvent e) {
       
   
    }
 
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelprincipal;
    private javax.swing.JMenuBar Ventas;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem saliendo;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
